### ISSUE TITLE
Acc on Test Set 

### ISSUE THREAD

**Issue by jianguoz** [SKTBrain/SUMBT#4]
During data preprocessing, all values not appeared in ontology are marked as  `none`, this assumption is too strong as the ontology could be incomplete. This is true for the MultiWoz dataset as there are many such values in the dataset. This processing way also changes the test set (>10% data), which provides an unfair comparison to other baselines. Moreover, this assumption results in much higher testing acc as predicting `none` is much easier.  Based on this method, maybe it is better to construct the ontology through traversing the dataset and report the real testing acc

**Comment by hwaranlee** [comment]
Hi @jianguoz 
Thank you for your comment. As you mentioned, dealing with slot-values not appearing in the ontology is debatable. However, we assumed the given pre-defined ontology is complete and follow the slot-value tables.

**Comment by jianguoz** [comment]
Thanks for your comment.
