### ISSUE TITLE
Results on Multiwoz2.1

### ISSUE THREAD

**Issue by SparkJiao** [SKTBrain/SUMBT#6]
Hi, sorry to bother you.

I have a small question that will you conduct an experiment on multiwoz2.1?

Thank you very much!

**Comment by jinsik-lee** [comment]
> Hi, sorry to bother you.
> 
> I have a small question that will you conduct an experiment on multiwoz2.1?
> 
> Thank you very much!

Currently, I don't have the plan. I am just wondering, may I ask the reason?

**Comment by SparkJiao** [comment]
Yes, there is a [paper](https://arxiv.org/abs/1910.03544) use a similar model(but different ways to search answer) with yours but get a much higher accuracy on multiwoz2.1 than **TRADE**. Indeed, in their experiments, **TRADE** has a great drop on joint accuracy compared with that on multiwoz2.0. In my own experiments, SUMBT will get a higher accuracy on multiwoz2.1 which indicates that the version2.1 is somehow easier that version 2.0. That's what puzzles me.
